# Gate proxy configuration for Minecraft Java Edition
config:
  # The bind address to listen for Minecraft client connections.
  bind: 0.0.0.0:25565
  
  onlineMode: true
  
  servers:
  
  try:
  
  acceptTransfers: true
 
  bungeePluginChannelEnabled: true
  
  forwarding:
    mode: velocity
    velocitySecret : balle123
api:
  enabled: true
  bind: localhost:8080
